// app/src/components/AgentPixelLoader.tsx
const PIXEL_DELAYS = [90, 180, 270, 0, 90, 180, 90, 180, 270]

export default function AgentPixelLoader({
  label,
  elapsed,
  running = false,
  compact = false,
}: {
  label?: string
  elapsed?: string
  running?: boolean
  compact?: boolean
}) {
  return (
    <span
      className={`agent-pixel-loader${compact ? ' agent-pixel-loader--compact' : ''}`}
      role="status"
      aria-label={[label, elapsed].filter(Boolean).join(' ')}
    >
      {running ? (
        <span className="agent-pixel" aria-hidden="true">
          {PIXEL_DELAYS.map((delay, index) => (
            <span
              key={index}
              className="agent-pixel__cell"
              style={{ animationDelay: `${delay}ms` }}
            />
          ))}
        </span>
      ) : null}
      {label && !compact ? (
        <span className={`agent-pixel-loader__label${running ? ' agent-pixel-loader__label--run' : ''}`}>
          {label}
        </span>
      ) : null}
      {elapsed ? <span className="agent-pixel-loader__elapsed">{elapsed}</span> : null}
    </span>
  )
}

// app/src/components-vue/AgentPixelLoader.vue
<script setup lang="ts">
const PIXEL_DELAYS = [90, 180, 270, 0, 90, 180, 90, 180, 270]

withDefaults(defineProps<{
  label?: string
  elapsed?: string
  running?: boolean
  compact?: boolean
}>(), {
  running: false,
  compact: false,
})
</script>

<template>
  <span
    class="agent-pixel-loader"
    :class="{ 'agent-pixel-loader--compact': compact }"
    role="status"
    :aria-label="[label, elapsed].filter(Boolean).join(' ')"
  >
    <span
      v-if="running"
      class="agent-pixel"
      aria-hidden="true"
    >
      <span
        v-for="(delay, index) in PIXEL_DELAYS"
        :key="index"
        class="agent-pixel__cell"
        :style="{ animationDelay: `${delay}ms` }"
      />
    </span>
    <span
      v-if="label && !compact"
      class="agent-pixel-loader__label"
      :class="{ 'agent-pixel-loader__label--run': running }"
    >{{ label }}</span>
    <span
      v-if="elapsed"
      class="agent-pixel-loader__elapsed"
    >{{ elapsed }}</span>
  </span>
</template>
