// app/src/components/RelatedCvePanel.tsx
import { useEffect, useState } from 'react'
import MarkdownContent from '@/components/MarkdownContent'
import { invokeCommand } from '@/desktop'
import type { CodingArtifactPreview } from '@/codingEnvironmentTypes'

export default function RelatedCvePanel({
  workspacePath,
  refreshKey,
  className,
}: {
  workspacePath: string
  refreshKey?: number | string | boolean
  className?: string
}) {
  const [preview, setPreview] = useState<CodingArtifactPreview | null>(null)

  useEffect(() => {
    let cancelled = false
    async function load() {
      const workspace = workspacePath.trim()
      if (!workspace) {
        if (!cancelled) setPreview(null)
        return
      }
      try {
        const next = await invokeCommand<CodingArtifactPreview>('get_coding_artifact_preview', {
          workspacePath: workspace,
          relativePath: 'related.md',
        })
        if (!cancelled) setPreview(next)
      } catch {
        if (!cancelled) setPreview(null)
      }
    }
    void load()
    return () => {
      cancelled = true
    }
  }, [workspacePath, refreshKey])

  return (
    <article className={className ? `related-cve-panel ${className}` : 'related-cve-panel'} data-testid="related-cves">
      {preview?.kind === 'markdown' && preview.content ? (
        <MarkdownContent content={preview.content} />
      ) : null}
    </article>
  )
}

// app/src/components-vue/RelatedCvePanel.vue
<script setup lang="ts">
import { onMounted, ref, watch } from 'vue'
import MarkdownContent from '@/components-vue/MarkdownContent.vue'
import { invokeCommand } from '@/desktop'
import type { CodingArtifactPreview } from '@/codingEnvironmentTypes'

const props = defineProps<{
  workspacePath: string
  refreshKey?: number | string | boolean
}>()

const preview = ref<CodingArtifactPreview | null>(null)

async function load() {
  const workspace = props.workspacePath.trim()
  if (!workspace) {
    preview.value = null
    return
  }
  try {
    preview.value = await invokeCommand<CodingArtifactPreview>('get_coding_artifact_preview', {
      workspacePath: workspace,
      relativePath: 'related.md',
    })
  } catch {
    preview.value = null
  }
}

onMounted(load)
watch(() => [props.workspacePath, props.refreshKey], load)
</script>

<template>
  <article class="related-cve-panel" data-testid="related-cves">
    <MarkdownContent v-if="preview?.kind === 'markdown' && preview.content" :content="preview.content" />
  </article>
</template>
