// app/src/components/WorkspaceModuleTopBar.tsx
import type { ReactNode } from 'react'
import WorkspaceTopBar from '@/components/WorkspaceTopBar'

export default function WorkspaceModuleTopBar({
  module,
  title,
  subtitle,
  hideIdentity,
  leading,
  badge,
  actions,
  filters,
  metrics,
}: {
  module: 'coding' | 'ctf' | 'cve' | 'lab'
  title?: string
  subtitle?: string
  hideIdentity?: boolean
  leading?: ReactNode
  badge?: ReactNode
  actions?: ReactNode
  filters?: ReactNode
  metrics?: ReactNode
}) {
  const fallbackTitle = { coding: 'Coding', ctf: 'CTF', cve: 'CVE', lab: 'LAB' }[module]
  const resolvedTitle = title?.trim() || fallbackTitle

  return (
    <WorkspaceTopBar
      module={module}
      title={resolvedTitle}
      subtitle={hideIdentity ? undefined : subtitle}
      hideIdentity={hideIdentity}
      leading={leading}
      badge={badge}
      actions={actions}
      filters={filters}
      metrics={metrics}
    />
  )
}

// app/src/components-vue/WorkspaceModuleTopBar.vue
<script setup lang="ts">
import { computed } from 'vue'
import WorkspaceTopBar from '@/components-vue/WorkspaceTopBar.vue'

const props = defineProps<{
  module: 'coding' | 'ctf' | 'cve' | 'lab'
  title?: string
  subtitle?: string
  hideIdentity?: boolean
}>()

const fallbackTitle = computed(() => ({
  coding: 'Coding',
  ctf: 'CTF',
  cve: 'CVE',
  lab: 'LAB',
})[props.module])
const resolvedTitle = computed(() => props.title?.trim() || fallbackTitle.value)
</script>

<template>
  <WorkspaceTopBar
    :module="module"
    :title="resolvedTitle"
    :subtitle="hideIdentity ? undefined : subtitle"
    :hide-identity="hideIdentity"
    data-workspace-module-topbar
  >
    <template v-if="$slots.leading" #leading>
      <slot name="leading" />
    </template>
    <template v-if="$slots.badge" #badge>
      <slot name="badge" />
    </template>
    <template v-if="$slots.actions" #actions>
      <slot name="actions" />
    </template>
    <template v-if="$slots.filters" #filters>
      <slot name="filters" />
    </template>
    <template v-if="$slots.metrics" #metrics>
      <slot name="metrics" />
    </template>
  </WorkspaceTopBar>
</template>
