// app/src/components-vue/AkLoadingMark.vue
<script setup lang="ts">
import { computed } from 'vue'
import { t } from '@/lib/uiLocale'

const props = withDefaults(defineProps<{
  label?: string
  showLabel?: boolean
}>(), {
  showLabel: false,
})

const resolvedLabel = computed(() => props.label ?? t('进行中', 'In progress'))
</script>

<template>
  <span
    class="ak-loading-host"
    :class="{ 'ak-loading-host--labeled': showLabel }"
    role="status"
    :aria-label="resolvedLabel"
  >
    <span class="ak-loading ak-loading--compact" aria-hidden="true" />
    <span v-if="showLabel" class="ak-loading-host__label">{{ resolvedLabel }}</span>
  </span>
</template>

// app/src/components/AkLoadingMark.tsx
import { useT } from '@/hooks/useUiLocale'
import { cn } from '@/lib/cn'

export default function AkLoadingMark({
  label,
  showLabel = false,
}: {
  label?: string
  showLabel?: boolean
}) {
  const t = useT()
  const resolvedLabel = label ?? t('进行中', 'In progress')
  return (
    <span
      className={cn('inline-flex items-center gap-2', showLabel && 'text-caption text-muted-foreground')}
      role="status"
      aria-label={resolvedLabel}
    >
      <span
        className="size-3.5 shrink-0 animate-spin rounded-full border-2 border-border border-t-foreground"
        aria-hidden="true"
      />
      {showLabel ? <span>{resolvedLabel}</span> : null}
    </span>
  )
}
