// app/src/components-vue/CTFWorkspaceHeader.vue
<script setup lang="ts">
import { Badge, Button } from '@felinic/ui'
import { ArrowLeft, Cable } from 'lucide-vue-next'
import WorkspaceModuleTopBar from '@/components-vue/WorkspaceModuleTopBar.vue'
import { t } from '@/lib/uiLocale'

defineProps<{
  challengeTitle?: string
  browserStatus?: 'off' | 'live' | ''
}>()

defineEmits<{
  returnCatalog: []
  openBrowserSettings: []
  refreshBridge: []
}>()
</script>

<template>
  <WorkspaceModuleTopBar module="ctf" :subtitle="t('解题会话', 'Solving session')">
    <template #leading>
      <Button variant="ghost" size="icon-sm" :aria-label="t('返回 CTF 题库', 'Back to CTF catalog')" @click="$emit('returnCatalog')">
        <ArrowLeft class="size-4" />
      </Button>
    </template>
    <template #badge>
      <Badge v-if="challengeTitle" variant="secondary" class="max-w-[18rem] truncate">
        {{ challengeTitle }}
      </Badge>
    </template>
    <template #actions>
      <Button
        v-if="browserStatus"
        variant="ghost"
        size="icon-sm"
        :aria-label="browserStatus === 'live' ? t('浏览器已连接', 'Browser connected') : t('浏览器未连接，打开设置', 'Browser disconnected, open settings')"
        :title="browserStatus === 'live' ? t('浏览器已连接', 'Browser connected') : t('浏览器未连接', 'Browser disconnected')"
        @click="browserStatus === 'live' ? $emit('refreshBridge') : $emit('openBrowserSettings')"
      >
        <Cable class="size-4" :class="browserStatus === 'live' ? 'text-foreground' : 'text-muted-foreground'" />
        <span
          class="ak-status ak-status--compact sr-only"
          :class="browserStatus === 'live' ? '' : 'ak-status--offline'"
        >
          {{ browserStatus === 'live' ? 'LIVE' : 'OFF' }}
        </span>
      </Button>
    </template>
  </WorkspaceModuleTopBar>
</template>

// app/src/components/CTFWorkspaceHeader.tsx
import { ArrowLeft, Cable } from 'lucide-react'
import { Badge, Button } from '@/components/ui'
import ConnectionLiveStatus from '@/components/ConnectionLiveStatus'
import WorkspaceModuleTopBar from '@/components/WorkspaceModuleTopBar'
import { useT } from '@/hooks/useUiLocale'

export default function CTFWorkspaceHeader({
  challengeTitle,
  browserStatus,
  onReturnCatalog,
  onOpenBrowserSettings,
  onRefreshBridge,
}: {
  challengeTitle?: string
  browserStatus?: 'off' | 'live' | ''
  onReturnCatalog?: () => void
  onOpenBrowserSettings?: () => void
  onRefreshBridge?: () => void
}) {
  const t = useT()
  return (
    <WorkspaceModuleTopBar
      module="ctf"
      subtitle={t('解题会话', 'Solving session')}
      leading={(
        <Button variant="ghost" size="icon-sm" aria-label={t('返回 CTF 题库', 'Back to CTF catalog')} onClick={onReturnCatalog}>
          <ArrowLeft className="size-4" />
        </Button>
      )}
      badge={challengeTitle ? (
        <Badge variant="secondary" className="max-w-[18rem] truncate">
          {challengeTitle}
        </Badge>
      ) : null}
      actions={browserStatus ? (
        <Button
          variant="outline"
          size="sm"
          className="app-no-drag shrink-0"
          data-connection-live-action
          aria-label={browserStatus === 'live' ? t('浏览器已连接', 'Browser connected') : t('浏览器未连接，打开设置', 'Browser disconnected, open settings')}
          title={browserStatus === 'live' ? t('浏览器已连接', 'Browser connected') : t('浏览器未连接', 'Browser disconnected')}
          onClick={browserStatus === 'live' ? onRefreshBridge : onOpenBrowserSettings}
        >
          <span className="connection-live-action__label">
            <Cable className="size-4" />
            {browserStatus === 'live' ? t('浏览器已连接', 'Browser connected') : t('连接浏览器', 'Connect browser')}
          </span>
          <ConnectionLiveStatus live={browserStatus === 'live'} decorative />
        </Button>
      ) : null}
    />
  )
}
